### ISSUE TITLE
Upload a file with os_version configuration

### ISSUE THREAD

**Issue by rogercoll** [newrelic/infrastructure-publish-action#137]
Uploading a file of type `file` with a os_version configuration does not make any effect. For example, the following schema won't expand the {os_version} variable:

```yaml
- src: "newrelic-infra-{version}-1.amazonlinux-{os_version}.{arch}.rpm.sum"
  arch:
    - x86_64
    - arm
    - arm64
  uploads:
    - type: file
      dest: "{dest_prefix}linux/yum/amazonlinux/{os_version}/{arch}/"
      os_version:
        - 2
        - 2022
```

In the other hand, with download it takes effect.
